## Quickstart tutorial
https://docs.scipy.org/doc/numpy/user/quickstart.html

In [1]:
import numpy as np

### The basics

#### ndarray attributes

In [6]:
a = np.arange(15).reshape(3,5)

In [9]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)
print(a.itemsize)
print(a.data)
print(type(a))

(3, 5)
2
15
int64
8
<class 'numpy.ndarray'>


#### Array Creation

you can create an array from a regular Python list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in the sequences.

In [13]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [15]:
# array transforms sequences of sequences into two-dimensional arrays, 
# sequences of sequences of sequences into three-dimensional arrays, and so on.
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

In [17]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [18]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
np.empty((3,4),dtype=int)

array([[                  0, 6917537789660388404,                   6,
                          0],
       [                  0, 3904177109877286251, 3270518443920156259,
        7221860846205481526],
       [3759768347749723443, 3545847158399066929, 8386112019186136419,
           1688849860293493]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(0,3,7)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ])

In [27]:
np.random.rand(5)

array([ 0.548066  ,  0.61970003,  0.83835501,  0.93906353,  0.79262753])

In [29]:
np.random.randn(5)

array([-0.9726042 ,  1.38167066, -1.16788979,  0.70385718,  0.07275172])

#### printing arrays

In [34]:
a = np.arange(6)
print(a.__repr__())
print(a)

array([0, 1, 2, 3, 4, 5])
[0 1 2 3 4 5]


In [37]:
b = np.arange(12).reshape(3,4)
print(b.__repr__())
print(b)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
c = np.arange(24).reshape(2,3,4)
print(c.__repr__())
print(c)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


#### Basic Operations

In [43]:
# arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.
a = np.array( [20,30,40,50] )
b = np.arange(4)
c = a - b
c

array([20, 29, 38, 47])

In [44]:
b ** 2

array([0, 1, 4, 9])

In [45]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [46]:
a < 35

array([ True,  True, False, False], dtype=bool)

In [48]:
# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one.
a = np.ones((2,3), dtype = int)
b = np.random.rand(2,3)
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [52]:
b += a
b

array([[ 9.90452013,  9.49266085,  9.96339779],
       [ 9.85897228,  9.05651537,  9.73796049]])

In [58]:
# Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.
print(a.sum())
print(a.min())
print(a.max())

18
3
3


In [59]:
# By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
# However, by specifying the axis parameter you can apply an operation along the specified axis of an array:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [61]:
b.sum(axis=1) # sum of each row

array([ 6, 22, 38])

In [62]:
b.cumsum(axis=1)  # cumulative sum of each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

#### Universal Functions

In [64]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [65]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [66]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ])

In [67]:
np.argmax(a)

4

In [68]:
np.argmin(a)

0

#### Indexing, Slicing, and Iterating

In [70]:
# One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [71]:
a[2]

8

In [72]:
a[2:5]

array([ 8, 27, 64])

In [73]:
a[:6:2]

array([ 0,  8, 64])

In [74]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [82]:
[num for num in a]

[0, 1, 8, 27, 64, 125, 216, 343, 512, 729]

In [84]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:
def f(x,y):
    return 10 * x + y

a = np.fromfunction(f,(5,4),dtype=int)
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [85]:
a[2,3]

23

In [86]:
a[:, 1] # second column

array([ 1, 11, 21, 31, 41])

In [87]:
a[1:3,:] # second and third row

array([[10, 11, 12, 13],
       [20, 21, 22, 23]])

In [88]:
# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:
a[0]

array([0, 1, 2, 3])

In [89]:
a[0,...]

array([0, 1, 2, 3])

In [92]:
[row.tolist() for row in a]

[[0, 1, 2, 3],
 [10, 11, 12, 13],
 [20, 21, 22, 23],
 [30, 31, 32, 33],
 [40, 41, 42, 43]]

In [93]:
[i for i in a.flat]

[0, 1, 2, 3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40, 41, 42, 43]